### ISSUE TITLE
 ruamel_yaml.scanner.ScannerError: mapping values are not allowed here

### ISSUE THREAD

**Issue by bgp799** [anwarMZ/CoMW#8] opened 2020-06-13 08:47 UTC
Hi, I get the following error when I retry to create environment (see below) with your revised CoMW.yml file. I also reinstalled anaconda to ensure that it wasn't the installation of Anaconda which was problematic. I have copied the error message here. I hope that you can help with this.
Kr,
Jon

(base) bgp799@pallas:/mibi/Jon/CoMW$ conda env create -f ./CoMW.yml

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 80, in execute
        directory=os.getcwd())
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/conda_env/specs/__init__.py", line 40, in detect
        if spec.can_handle():
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/conda_env/env.py", line 151, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/conda_env/env.py", line 136, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 76, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/ruamel_yaml/constructor.py", line 109, in get_single_data
        node = self.composer.get_single_node()
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 104, in compose_document
        self.parser.get_event()
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 163, in get_event
        self.current_event = self.state()
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 239, in parse_document_end
        token = self.scanner.peek_token()
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 182, in peek_token
        self.fetch_more_tokens()
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 282, in fetch_more_tokens
        return self.fetch_value()
      File "/mibi/Jon/anaconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 655, in fetch_value
        self.reader.get_mark(),
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 121, column 73:
         ... r-bar top-0 left-0" style="width: 0%;"></span>
                                             ^ (line: 121)

`$ /mibi/Jon/anaconda3/bin/conda-env create -f ./CoMW.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/mibi/Jon/anaconda3/bin/conda
             CONDA_PREFIX=/mibi/Jon/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/mibi/Jon/anaconda3/bin/python
               CONDA_ROOT=/mibi/Jon/anaconda3
              CONDA_SHLVL=1
          LD_LIBRARY_PATH=/root/install/ncbi-blast-2.4.0+-src/c++/local/ncbi-vdb-2.6.1/lib64:
                     PATH=/mibi/Jon/anaconda3/bin:/mibi/Jon/anaconda3/bin:/mibi/Jon/anaconda3/co
                          ndabin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/
                          bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /mibi/Jon/anaconda3
            shell level : 1
       user config file : /usr/local/home/bgp799/.condarc
 populated config files : /usr/local/home/bgp799/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.28
       base environment : /mibi/Jon/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mibi/Jon/anaconda3/pkgs
                          /usr/local/home/bgp799/.conda/pkgs
       envs directories : /mibi/Jon/anaconda3/envs
                          /usr/local/home/bgp799/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Linux/4.19.0-9-amd64 debian/10 glibc/2.28
                UID:GID : 3047:3000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

**Comment by anwarMZ** [comment] 2020-06-21 16:28
Hi Jon, 
Its a bit strange to see this error, i have tried to reproduce it by using the latest `CoMW.yml` file but it works well for me. I also asked another colleague who was trying to use CoMW and it worked well for him too. Could this be an error due to `anaconda` in the system? I saw that you reinstalled it. but maybe the cache wasn't clear? Could you try this before installing again?

`conda clean -a`

Best, 
Zohaib

**Comment by bgp799** [comment] 2020-06-26 09:46
Hi Zohaib, I tried again with "conda clean -a" and it removed many packages. I did this the last time as well. After, I tried:

(base) bgp799@pallas:/mibi/Jon/CoMW$ conda env create -f ./CoMW.yml

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 80, in execute
        directory=os.getcwd())
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/conda_env/specs/__init__.py", line 40, in detect
        if spec.can_handle():
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/conda_env/env.py", line 151, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/conda_env/env.py", line 136, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 76, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/ruamel_yaml/constructor.py", line 109, in get_single_data
        node = self.composer.get_single_node()
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 104, in compose_document
        self.parser.get_event()
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 163, in get_event
        self.current_event = self.state()
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 239, in parse_document_end
        token = self.scanner.peek_token()
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 182, in peek_token
        self.fetch_more_tokens()
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 282, in fetch_more_tokens
        return self.fetch_value()
      File "/usr/local/home/bgp799/anaconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 655, in fetch_value
        self.reader.get_mark(),
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 121, column 73:
         ... r-bar top-0 left-0" style="width: 0%;"></span>
                                             ^ (line: 121)

`$ /usr/local/home/bgp799/anaconda3/bin/conda-env create -f ./CoMW.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/usr/local/home/bgp799/anaconda3/bin/conda
             CONDA_PREFIX=/usr/local/home/bgp799/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/usr/local/home/bgp799/anaconda3/bin/python
               CONDA_ROOT=/usr/local/home/bgp799/anaconda3
              CONDA_SHLVL=1
          LD_LIBRARY_PATH=/root/install/ncbi-blast-2.4.0+-src/c++/local/ncbi-vdb-2.6.1/lib64:
                     PATH=/usr/local/home/bgp799/anaconda3/bin:/usr/local/home/bgp799/anaconda3/
                          bin:/usr/local/home/bgp799/anaconda3/bin:/usr/local/home/bgp799/anacon
                          da3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:
                          /snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /usr/local/home/bgp799/anaconda3
            shell level : 1
       user config file : /usr/local/home/bgp799/.condarc
 populated config files : /usr/local/home/bgp799/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.28
       base environment : /usr/local/home/bgp799/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/home/bgp799/anaconda3/pkgs
                          /usr/local/home/bgp799/.conda/pkgs
       envs directories : /usr/local/home/bgp799/anaconda3/envs
                          /usr/local/home/bgp799/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/4.19.0-9-amd64 debian/10 glibc/2.28
                UID:GID : 3047:3000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y

**Comment by bgp799** [comment] 2020-06-26 09:48
Hi, I checked that there was nothing to remove with a second time:
(base) bgp799@pallas:/mibi/Jon/CoMW$ conda clean -a
Cache location: 
There are no tarballs to remove
WARNING: /usr/local/home/bgp799/.conda/pkgs does not exist
Cache location: 
There are no unused packages to remove

**Comment by anwarMZ** [comment] 2020-06-30 18:57
Hi, I had a chance to review this but so far i am not sure what is the reason that you get this error. I tried to install on a few machines and it worked well on all of them. I might need some more time to figure out the reason.

**Comment by bgp799** [comment] 2020-07-08 09:30
Hi, I am starting to run out of time and I have to try something. Perhaps I should try to remove anaconda environment altogether and reinstall again?
Kr,
Jon

**Comment by anwarMZ** [comment] 2020-07-09 06:31
Hi @bgp799, I am not sure how the error is at your system. I have tried to install it on multiple systems and still haven't got the error even once. Anyways, I tried to search for it and i believe the error was in parsing `CoMW.yml` file. I have validated it and changed the structure a bit. Could you try to download the 'CoMW.yml' and try

`conda env create -f ./CoMW.yml`


Make sure you don't have another `conda` env named `CoMW`. Incase you have one, delete the env by 
`conda remove --name CoMW --all` before making a new one.

**Comment by anwarMZ** [comment] 2020-07-16 01:52
I will take it as if the problem was solved. I am closing this now. Please feel free to reopen if you still have issues.

**Closed as completed by anwarMZ** 2020-07-16 01:52 UTC
Labels: bug
